### ISSUE TITLE
Add Freedesktop runtime on Readme Plz!

### ISSUE THREAD

**Issue by alex285** [kirbyfan64/adwaita-refresh-installer#2]
can you please add this on README! I got bored to answer on comments about this :)

```
flatpak install flathub org.freedesktop.Sdk/x86_64/18.08
```

**Comment by AdrianVovk** [comment]
@kirbyfan64 Actually, you don't even need the freedesktop Sdk per se...

For carbonOS, I just use org.freedeskop.Platform as the SDK and it works fine, as long as you just want to copy files...
